### ISSUE TITLE
Rounding issue for negative numbers

### ISSUE THREAD

**Issue by hmaurer** [socraticorg/mathsteps#72] opened 2017-01-20 11:28 UTC
The "simplify arithmetic" strategy rounds to precision 4 automatically. This makes sense for decimal numbers (c.f. https://github.com/socraticorg/mathsteps/issues/64) but leads to confusing behaviour with large numbers. For example, the expression `16 + -1953125` simplifies in a single step to `-1953000`. 

Granted, students learning arithmetic usually do not work with large numbers, but they can easily pop up in expressions with powers.

Code: https://github.com/socraticorg/mathsteps/blob/master/lib/simplifyExpression/arithmeticSearch/index.js#L53

**Comment by evykassirer** [comment] 2017-01-20 16:39
Hm, wait really?

I think `toFixed` only rounds after the decimal point.

<img width="317" alt="screen shot 2017-01-20 at 11 38 24 am" src="https://cloud.githubusercontent.com/assets/5634097/22157261/00a49904-df05-11e6-93b9-76d17ad9885c.png">

I'm confused where you'd get the rounding to `-1953000` (but eager to find out!)

**Comment by hmaurer** [comment] 2017-01-20 17:15
@evykassirer I haven't inserted a `console.log` to check, but I think since `-1953125 < 1` it executes line 54 (https://github.com/socraticorg/mathsteps/blob/master/lib/simplifyExpression/arithmeticSearch/index.js#L54) and 

```
> parseFloat((-1953125).toPrecision(4))
- 1953000
```

**Comment by evykassirer** [comment] 2017-01-20 17:17
OMG amazing. Thanks for finding that. So it just needs to be changed to `if (-1 < result < 1) {` then, yeah?

**Comment by hmaurer** [comment] 2017-01-20 17:22
I think so; I am not quite sure that the goal of that line was (use toPrecision instead of toFixed when < 1) but if you say so!

By the way, I found this error by writing a generative test (like Haskell's Quickcheck) for `simplifyExpression`. It ended up being quite useless; the project seems very well tested and my code found errors which were just missing implementations, but yeah...

**Comment by evykassirer** [comment] 2017-01-20 17:32
oh, we should add a comment there then! (you can add it if you decide to take on this PR)

`toFixed` makes sense in most cases, and rounds to 4 digits after the decimal.

However, for something like 0.0000834567, it'd be nice to keep 4 digits of accuracy, not including the leading 0s (ie round to 0.00008346). So `toPrecision` is used to keep precision for small numbers (ones that don't have any digits before the decimal point). That's why it should be changed to `-1 < 0 < 1` -- I guess we just forgot that negative numbers exist when writing this 😛

**Comment by evykassirer** [comment] 2017-01-20 17:33
Also neat that you tried that - I'm super glad our tests are solid!! Great to hear.

If anything wasn't implemented but didn't have an issue for implementing it in the future (and you think it would be nice to cover) feel free to make an issue for it!

**Comment by evykassirer** [comment] 2017-01-21 01:25
added the small tag, cause it's a one line fix.

**Comment by emars** [comment] 2017-01-21 13:22
I looked at this for ~15 minutes, adding that case causes a regression in test:
`test/solveEquation/solveEquation.test.js` for case:

`solveEquation for = ( u )/( 0.3) = 4u + 6.28 -> u = -9.42:`

expected: `-9.4195`
actual: `-9.42`

Am I good to change the expectation to `-9.42` now that the precision is changed?

**Comment by evykassirer** [comment] 2017-01-21 19:27
thanks for taking this on!

It's actually expecting  `-9.42` (which is the **right answer**) and getting  `-9.4195` ... so that's too bad :(

But the only reason it was getting the answer right before was because it was rounding to `-9.420`, so it was just rounding luckily. This is an issue that was already happening, so your change didn't create the problem, it just revealed it for this case.

I think the best thing to do here is comment out that test and move it below the comment about rounding errors (a few lines lower). We've been doing a bunch of thinking about solutions in #64 if you're interested.

How's that sound?

**Comment by evykassirer** [comment] 2017-02-10 03:29
@emars just checking in - how's this going? need help with anything?

**Comment by emars** [comment] 2017-02-10 17:40
Hey sorry, I got busy with work and completely forgot lol.

I'll tackle this tomorrow unless somebody else is interested. Let me know.

**Comment by evykassirer** [comment] 2017-02-10 20:22
no problem - that's why I asked haha

go for it! it's still assigned to you :)

**Comment by evykassirer** [comment] 2017-04-12 16:19
@emars still wanna tackle this? 

(if you're not free/interested that's fine -  we can open it up as a good first issue for newcomers)

**Comment by evykassirer** [comment] 2017-04-29 01:50
I'm going to close this and use a new issue to more accurately describe the issue for newcomers :)

**Closed by evykassirer** 2017-04-29 01:50 UTC
Labels: bug, small
